# Найти с помощью NumPy SVD для матрицы


In [2]:
import numpy as np

In [3]:
matrix = np.array([
    [1,2,0],
    [0,0,5],
    [3,-4,2],
    [1,6,5],
    [0,1,0],
])

In [7]:
## A = U*D*V^T

U,s,W = np.linalg.svd(matrix)
s

array([8.82486885, 6.14060608, 2.53271528])

In [9]:
D = np.zeros_like(matrix, dtype=float)
D[np.diag_indices(min(matrix.shape))] = s

In [10]:
V = W.T

In [11]:
print(f"U = {U}\nD = {D}\nV = {V}")

U = [[ 0.17056501  0.15680918 -0.53077508 -0.79905375 -0.16158397]
 [ 0.39287016 -0.52933945  0.6134793  -0.43375771  0.03082495]
 [-0.14366152 -0.82449256 -0.52379105  0.14049848  0.07400343]
 [ 0.88843702  0.06074346 -0.24655277  0.37755832 -0.06042632]
 [ 0.08125046  0.10831843 -0.08231425 -0.10524851  0.98173958]]
D = [[8.82486885 0.         0.        ]
 [0.         6.14060608 0.        ]
 [0.         0.         2.53271528]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
V = [[ 0.07116451 -0.36737824 -0.92734505]
 [ 0.71702467  0.66514082 -0.20847855]
 [ 0.69340553 -0.65009301  0.31075368]]


In [12]:
A = U.dot(D.dot(V.T))

In [14]:
# Получаем исходную матрицу
A

array([[ 1.00000000e+00,  2.00000000e+00,  6.66133815e-16],
       [ 1.11022302e-15, -2.22044605e-15,  5.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00,  2.00000000e+00],
       [ 1.00000000e+00,  6.00000000e+00,  5.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00,  0.00000000e+00]])

## 

##    Для матрицы из предыдущего задания найти:

##    а) евклидову норму;

##    б) норму Фробениуса.


In [16]:
e_norm = s[0]
e_norm

8.824868854820442

In [22]:
f_norm = (s*s).sum()
f_norm

122.0